name: Build and Run Tests

on:
  push:
    branches:
      - main    # Specify the branch you want to run the tests on
  pull_request:
    branches:
      - main    # Optional: run on pull requests to 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm clang libclang-dev cmake make

      - name: Build the app
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run tests
        run: |
          cd build/test          # Navigate to your test directory
          ./run_test_script.sh    # Replace this with your test script's actual name
